# Generated by Django 4.1.8 on 2023-09-17 01:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0015_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Pedidos',
        ),
    ]
