# Generated by Django 4.1.8 on 2023-09-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_rename_orders_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.products')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.vendedores')),
            ],
        ),
    ]
